services:
  prowlarr:
    container_name: prowlarr
    image: bitlessbyte/prowlarr:latest
    command: /app/prowlarr/bin/Prowlarr
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
