#!/usr/bin/with-contenv bash

# Change to the correct directory
cd /app/prowlarr/bin

# Remove any stale lock files
rm -f /config/*.pid /config/prowlarr.pid

# Start Prowlarr with basic s6 user switching
exec s6-setuidgid abc ./Prowlarr -nobrowser -data=/config
