name: Build Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [external-repo-update]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - architecture: amd64
            dockerfile: Dockerfile
            platform: linux/amd64
            branch: master
          - architecture: amd64
            dockerfile: Dockerfile
            platform: linux/amd64
            branch: develop
          - architecture: arm64
            dockerfile: Dockerfile.aarch64
            platform: linux/arm64
            branch: master
          - architecture: arm64
            dockerfile: Dockerfile.aarch64
            platform: linux/arm64
            branch: develop

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: bitlessbyte/prowlarr:latest
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
        flavor: |
          suffix=-${{ matrix.architecture }},onlatest=true

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        platforms: ${{ matrix.platform }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          PROWLARR_BRANCH=${{ matrix.branch }}
        cache-from: type=gha
        cache-to: type=gha,mode=max